name: Mobile App Robot Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Robot Tests on Android Emulator
    runs-on: ubuntu-latest

    steps:
      - name: run tests
        run: |
          echo "Running robot tests on Android emulator"
          # Start the Android emulator
          $ANDROID_HOME/emulator/emulator -avd android_11 -no-window -no-audio -gpu swiftshader_indirect &

          # Wait for the emulator to start
          adb wait-for-device
          adb shell input keyevent 82 &

          # Run the robot tests
          robot --outputdir results --loglevel DEBUG tests/
