name: Mobile App Robot Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Robot Tests with APK from URL File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          pip install -r Libraries/requirement.txt
          pip install gdown
          npm install -g appium  # install Appium globally

      - name: Download APK from URL in Libraries/apkUrl.txt
        run: |
          URL=$(cat Libraries/apkUrl.txt)
          echo "Downloading APK from $URL"
          gdown "$URL" -O app.apk

      - name: Start Appium Server in Background
        run: |
          nohup appium > appium.log 2>&1 &
          echo "Appium server started"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Create and start emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;google_apis;x86_64"
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          nohup emulator -avd test -no-window -no-audio -no-snapshot &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          bootanim=""
          until [[ "$bootanim" == "stopped" ]]; do
            bootanim=$(adb shell getprop init.svc.bootanim 2>/dev/null | tr -d '\r')
            sleep 5
          done
          echo "✅ Emulator ready"

      - name: Restart ADB server
        run: |
          adb kill-server
          adb start-server
        
      - name: Install APK on Emulator
        run: |
            adb install app.apk
        
      - name: Run Robot Framework Tests 
        run: |
            echo "🔎 Starting Robot Framework tests"
            robot -d results tests/

      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/